"""Adding breed

Revision ID: 72db0f53946d
Revises: 
Create Date: 2019-05-27 16:28:58.743451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72db0f53946d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
