"""created puppy db

Revision ID: 877e9996b751
Revises: 
Create Date: 2018-03-30 01:52:11.240799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '877e9996b751'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppies')
    # ### end Alembic commands ###
