"""added breed

Revision ID: 823b7933359c
Revises: fad2dc5de130
Create Date: 2018-03-29 16:01:25.953794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823b7933359c'
down_revision = 'fad2dc5de130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppies', sa.Column('breed', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppies', 'breed')
    # ### end Alembic commands ###
